### ISSUE TITLE
Add a headlight command

### ISSUE THREAD

**Issue by zjc2106** [Barnard-PL-Labs/esp32-tanks#10]
Headlight is PIN19

[X] add command that turns tank headlight on

**Comment by faustinacheng** [comment]
Added headlight control and integrated with command interface.
serial command: `light [brightness]`
where brightness is [0, 255] with 0 = off and 255 = full brightness.
Commit: [c9a81f0](https://github.com/Barnard-PL-Labs/esp32-tanks/commit/c9a81f03520cee486be678f53b4b3524fb0e9e54)
