### ISSUE TITLE
Establish wireless communication between laptop and tanks

### ISSUE THREAD

**Issue by chungus-v67** [Barnard-PL-Labs/esp32-tanks#13]
We need a wireless solution where the laptop can send/receive data to/from the tanks wirelessly WHILE being connected to the internet.

**Comment by chungus-v67** [comment]
These are the high level overviews of the two setups that I've been attempting to use:
[Network diagram example(2).pdf](https://github.com/Barnard-PL-Labs/esp32-tanks/files/14762509/Network.diagram.example.2.pdf)

**Comment by brennen-b** [comment]
We are going to stick with manually connecting the tanks as before

**Comment by chungus-v67** [comment]
We are going to stick with manually connecting the tanks as before

**Comment by santolucito** [comment]
does manually mean with serial? or manually typing in IPs?

**Comment by chungus-v67** [comment]
I meant serial, mainly. I realize this ticket wasn't well worded for the problem I was actually after, which was automating the handshake between the laptop and tank. Because once the laptop and tank have each other's IP's, we _should_ be able to use HTTP freely for the communication (certainly over the windows hotspot, though).
