### ISSUE TITLE
Tank instructions from Server

### ISSUE THREAD

**Issue by symoreios** [Barnard-PL-Labs/esp32-tanks#20]
Currently the flask server just pops the instruction on top of the stack and sends it to whichever tank sent a get request. 
This won't work when all 4 tanks are connected, need some sort of algorithm to send tanks the same instructions at the same time. As the tanks are currently sending get requests to the flask server, instead of the flask server pushing instructions to them, might need to either go back to a "push" set up somehow, or find some way on the flask side to ensure all 4 tanks get the same instructions at the same time.

**Comment by zjc2106** [comment]
Fixed in commit [b23fd0a](https://github.com/Barnard-PL-Labs/esp32-tanks/commit/b23fd0a29cf52d1f31753709c8799cb2bfd1a5f3) by keeping track of which tanks have ran each command (using their IPs). Need to test with multiple tanks.
